
import localFont from 'next/font/local';
import "./globals.css";

const myFont = localFont({
  name: 'Montserrat',
  src: '../fonts/montserrat/Montserrat-Bold.ttf',
  display: 'swap',
  variable: '--font-montserrat',
})

export const metadata = {
  title: "The Cocreate Group",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${myFont.className}`}>
        <main className="">{children}</main>
      </body>
    </html>
  );
}
