
import localFont from 'next/font/local';
import Head from 'next/head';
import "react-toastify/dist/ReactToastify.css";
import "./globals.css";

const myFont = localFont({
  name: 'Montserrat',
  src: [
    {
      path: '../fonts/montserrat/Montserrat-Regular.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../fonts/montserrat/Montserrat-Medium.ttf',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../fonts/montserrat/Montserrat-SemiBold.ttf',
      weight: '600',
      style: 'normal',
    },
    {
      path: '../fonts/montserrat/Montserrat-Bold.ttf',
      weight: '700',
      style: 'normal',
    },
  ],
  display: 'swap',
  variable: '--font-montserrat',
})

export const metadata = {
  title: "The Cocreate Group",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body className={`${myFont.className}`}>
        <main className="">{children}</main>

       
      </body>
    </html>
  );
}
